services:
  - type: web
    name: society-management-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_APP_PASSWORD
        sync: false
      - key: REDIS_HOST
        fromService:
          name: society-redis
          type: redis
          property: host
      - key: REDIS_PORT
        fromService:
          name: society-redis
          type: redis
          property: port
      - key: REDIS_PASSWORD
        fromService:
          name: society-redis
          type: redis
          property: password

  - type: redis
    name: society-redis
    plan: free
    maxmemoryPolicy: allkeys-lru