apiVersion: v1
kind: Secret
metadata:
  name: society-secrets
  namespace: society-management
type: Opaque
stringData:
  MONGODB_URI: MONGODB_URI=mongodb+srv://Suman_Mandal:zw53KjV6YFiAmPI9@cluster0.aqmaut2.mongodb.net/Society_DB?retryWrites=true&w=majority&connectTimeoutMS=10000&socketTimeoutMS=10000&maxPoolSize=50&minPoolSize=5
  JWT_SECRET: PgBRR9NDbSDi9GshN2C4RKqFqfMkhkbntucokTaXB7g=