apiVersion: v1
kind: Secret
metadata:
  name: society-secrets
  namespace: society-management
type: Opaque
stringData:
  MONGODB_URI: YOUR_MONGODB_URI_HERE
  JWT_SECRET: YOUR_JWT_SECRET_HERE
  SECURITY_PEPPER: YOUR_SECURITY_PEPPER_HERE
  MAIL_USERNAME: YOUR_MAIL_USERNAME_HERE
  MAIL_APP_PASSWORD: YOUR_MAIL_APP_PASSWORD_HERE
  AWS_ACCESS_KEY_ID: YOUR_AWS_ACCESS_KEY_ID_HERE
  AWS_SECRET_ACCESS_KEY: YOUR_AWS_SECRET_ACCESS_KEY_HERE
  RAZORPAY_KEY_ID: YOUR_RAZORPAY_KEY_ID_HERE
  RAZORPAY_KEY_SECRET: YOUR_RAZORPAY_KEY_SECRET_HERE
  RAZORPAY_WEBHOOK_SECRET: YOUR_RAZORPAY_WEBHOOK_SECRET_HERE
  PLATFORM_ADMIN_EMAIL: YOUR_PLATFORM_ADMIN_EMAIL_HERE
  PLATFORM_ADMIN_PASSWORD: YOUR_PLATFORM_ADMIN_PASSWORD_HERE
  REDIS_PASSWORD: YOUR_REDIS_PASSWORD_HERE
  FRONTEND_URL: YOUR_FRONTEND_URL_HERE