apiVersion: v1
kind: Service
metadata:
  name: society-management-svc
  namespace: society-management
spec:
  selector:
    app: society-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer